storage:
  filesystem:
    enabled: !ENV ${FILESYSTEM_ENABLED}
    data_root: datastore-testdata/example
  gcloud:
    enabled: !ENV ${GOOGLE_ENABLED}
    bucket: runpandarun-testbucket-storage
publish:
  handlers:
    filesystem:
      enabled: !ENV ${FILESYSTEM_PUBLISH_ENABLED}
      data_root: datastore-testdata/public
      base_url: http://localhost:8000
    gcloud:
      enabled: !ENV ${GOOGLE_PUBLISH_ENABLED}
      bucket: runpandarun-testbucket-publish
combine:
  - a_local_csv
  - a_local_json
datasets:
  my_dataset:
    csv_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vRhzhiVJr0XPcMANnb9_F7bcE6h-C5826MGJs034AocLpyo4uy0y97LIG2ns8F1heCrSTsyEkL1XwDK/pub?output=csv  # noqa
    columns:
      - id: identifier
      - value
      - date
  a_local_csv:
    csv_local: ./example/testdata.csv
    copy: true
    read:
      skipfooter: 1
    columns:
      - value: amount
      - state
      - date
    dt_index: date
    ops:
      - applymap:
          func: 'lambda x: x.lower() if isinstance(x, str) else x'
  a_local_json:
    json_local: ./example/testdata.json
    copy: true
    read:
      dtype:
        integer: str
    columns:
      - value: integer
      - state:
          map: 'lambda x: x.upper()'
      - date
    dt_index: date
  divi_reports:
    csv_url: https://www.divi.de/images/Dokumente/Tagesdaten_Intensivregister_CSV/DIVI_Intensivregister_{date}_09-15.csv
    request:
      url_replace:
        date: '(datetime.now() - timedelta(days=1)).date().isoformat()'
    index: gemeindeschluessel
